### ISSUE TITLE
Compiling the Geant3 legacy fortran code with Fortran 2018- compliant gfortran 10.2.1

### ISSUE THREAD

**Issue by olinart** [vmc-project/vmc#10]
The compilation of the legacy code now fails. This is fixed by adding the options to Geant3BuildLibrary.cmake

<-fallow-argument-mismatch -fallow-invalid-boz>
I don't know whether this needs to be conditional on gfortran_version>9 or whether it will be OK for older versions as well.

**Comment by ihrivnac** [comment]
Hi @olinart ,
The Geant3BuildLibrary.cmake was updated for GCC >= 10 in this geant3 update:  [bce6232](https://github.com/vmc-project/geant3/commit/bce62320af0cdce0bbc4bd9641868147dbed63b6)

Could you, please, check if you use the latest Geant3 version (3.7)?

**Comment by olinart** [comment]
Hi Ivana,

I checked and I was using version 2.72, so I missed the latest update. I 
can confirm that version 3.37 builds correctly.  The 
-fallow-argument-mismatch flag with GNU Fortran (GCC) 10.2.1 was needed 
for the legacy FFKEY code with 2.72 and it does remove the compilation 
warnings in 3.37.

Great that you picked up this problem.

On 2021-01-06 5:02 a.m., Ivana Hrivnacova wrote:
>
> Hi @olinart 
> <https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Folinart&data=04%7C01%7Colin%40triumf.ca%7Cb7746eec3c9e44ec434a08d8b24351fb%7Cc20535109cb34679a2d38f442e03b587%7C1%7C0%7C637455349495474785%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xemCMgY67df%2Fn%2BJa0rBJI%2BT472AFBBIn%2BGFmQcKp%2ByU%3D&reserved=0> 
> ,
> The Geant3BuildLibrary.cmake was updated for GCC >= 10 in this geant3 
> update: bce6232 
> <https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmc-project%2Fgeant3%2Fcommit%2Fbce62320af0cdce0bbc4bd9641868147dbed63b6&data=04%7C01%7Colin%40triumf.ca%7Cb7746eec3c9e44ec434a08d8b24351fb%7Cc20535109cb34679a2d38f442e03b587%7C1%7C0%7C637455349495474785%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7YUdiS6Df1GjeK5M7lYPCSBYuWrp8LlFpgRlSnXbgjc%3D&reserved=0>
>
> Could you, please, check if you use the latest Geant3 version (3.7)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmc-project%2Fvmc%2Fissues%2F10%23issuecomment-755286580&data=04%7C01%7Colin%40triumf.ca%7Cb7746eec3c9e44ec434a08d8b24351fb%7Cc20535109cb34679a2d38f442e03b587%7C1%7C0%7C637455349495484781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Mcr2EjKlFWBqIUXRJ9%2FNPSyfCyfIVL2rrLlRH3L4QWA%3D&reserved=0>, 
> or unsubscribe 
> <https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNKJH4D6ZCS6VMGIP3AC4LSYRNOHANCNFSM4VSJ7IPQ&data=04%7C01%7Colin%40triumf.ca%7Cb7746eec3c9e44ec434a08d8b24351fb%7Cc20535109cb34679a2d38f442e03b587%7C1%7C0%7C637455349495484781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P5DuvR0qEQgrEr4WQb05vL4AbOt3HLKpXbNqs1PeK7Q%3D&reserved=0>.
>
-- 

*Art Olin**
****Research Scientist Emeritus*
***TRIUMF* Canada's particle accelerator centre
*Adjunct Professor*
***University of Victoria* Department of Physics and Astronomy
t 604.222.7349 h 604.222.0650**
**_olin@triumf.ca_**
4004 Wesbrook Mall
Vancouver BC V6T 2A3 Canada**

**

****
**

**Comment by ihrivnac** [comment]
Hi @olinart ,

I have added the -fallow-argument-mismatch, see [e52caf623a](https://github.com/vmc-project/geant3/commit/e52caf623a5fa28a868e118a65dec773d7165c84). 
Thank you for proposing the fix.
