### ISSUE TITLE
AddIons() and InitGeometry() order

### ISSUE THREAD

**Issue by karabowi** [vmc-project/vmc#18]
In `TGeant3` AddIons() is called before InitGeometry():
   `fApplication->AddIons();`
   `fApplication->InitGeometry();`

On the contrary, the order of calling these functions in `TGeant4` is different:
   `fApplication->InitGeometry();`
   `fApplication->AddIons();`

Is it intended behavior?
Can it be changed so that the functions are called in the same order in both TGeant3 and TGeant4?

**Comment by ihrivnac** [comment]
Hi @karabowi ,

Yes, it is intended. The Geant4 initialization is performed via calling user classes, which are implemented in our case in Geant4 VMC, where we perform the calls to VMC Application  functions. This guarantees the correct behaviour in both sequential and MT modes.

Changing this would require to move a call to VMC Application  function (eg. AddIons) into a class not dedicated for ion construction, that could work fine in your application, but may cause problems in other ones.

We had never a requirement for calling the VMC Application function by the VMC interface in the same order, so users applications have to adapt their code to such situations.
